import Head from "next/head";
import { FaSun, FaMoon } from "react-icons/fa";
import { useEffect, useState } from "react";
import Intro from "./Intro";
import NodeGraphSkills from "./NodeGraphSkills";
import Contact from "./contact";
import Certificates from "./Certificates";
import Link from "next/link";
import MobileNav from "./MobileNav";

const Home = function () {
  const [darkMode, setDarkMode] = useState(true);
  const [isLargeScreen, setIsLargeScreen] = useState(false);
  const [isIntroScreenActive, setIsIntroScreenActive] = useState(true);

  useEffect(() => {
    const handleResize = () => {
      setIsLargeScreen(window.innerWidth >= 768);
    };
    window.addEventListener("resize", handleResize);
    handleResize();
    return () => window.removeEventListener("resize", handleResize);
  }, []);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Agnesh's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-4 dark:bg-gray-900 lg:px-10">
        <section className="flex min-h-screen flex-col justify-between">
          <nav className="mb-12 flex justify-between py-10 ">
            <div className="flex w-1/2 flex-row  text-center">
              {!isLargeScreen && (
                <MobileNav setIsActive={setIsIntroScreenActive} />
              )}
              <button
                className="ml-12 text-start font-poppins_semi_bold text-xl dark:text-white lg:ml-0"
                onClick={() => {
                  setIsIntroScreenActive(true);
                }}
              >
                My Portfolio
              </button>
              {isLargeScreen && (
                <ul className=" ml-10 flex w-60 flex-row justify-evenly dark:text-white">
                  <li className="text-x font-poppins_semi_bold dark:text-white">
                    <button onClick={() => setIsIntroScreenActive(false)}>
                      Certificates
                    </button>
                  </li>
                  <li className="text-x font-poppins_semi_bold dark:text-white">
                    <button onClick={() => setIsIntroScreenActive(false)}>
                      Projects
                    </button>
                  </li>
                </ul>
              )}
            </div>
            <ul className=" flex items-center dark:text-white">
              <li className="text-2xl lg:text-3xl">
                {darkMode ? (
                  <FaSun onClick={() => setDarkMode(!darkMode)} />
                ) : (
                  <FaMoon onClick={() => setDarkMode(!darkMode)} />
                )}
              </li>
              <li>
                <a
                  className=" ml-8 rounded-lg bg-gradient-to-r from-violet-500 to-purple-500 px-4 py-2 text-white hover:from-red-600 hover:to-red-500"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          {isIntroScreenActive && <Intro mode={darkMode} />}
          {isIntroScreenActive && <NodeGraphSkills />}
          {isIntroScreenActive && <Contact />}
          {!isIntroScreenActive && <Certificates />}
        </section>
      </main>
    </div>
  );
};

export default Home;
