import Head from "next/head";
import { FaSun, FaMoon } from "react-icons/fa";
import { useContext, useEffect } from "react";
import Intro from "./Intro";
import NodeGraphSkills from "./NodeGraphSkills";
import Certificates from "./Certificates";
import MobileNav from "./MobileNav";
import Projects from "./Projects";
import AppContext from "../state/AppContext";
import { pages } from "../state/AppProvider";
import SkillsSection from "./SkillsSection";
import Contact from "./Contact";

const Home = function () {
  const {
    darkMode,
    setDarkMode,
    isLargeScreen,
    setIsLargeScreen,
    currentPage,
    setCurrentPage,
  } = useContext(AppContext);

  useEffect(() => {
    const handleResize = () => {
      setIsLargeScreen(window.innerWidth >= 768);
    };
    window.addEventListener("resize", handleResize);
    handleResize();
    return () => window.removeEventListener("resize", handleResize);
  }, []);

  const downloadResume = function () {
    // fetch(
    //   "../public/assets/cloud_college.png"
    // ) // Replace 'path_to_your_file' with the actual file URL
    //   .then((response) => response.blob())
    //   .then((blob) => {
    //     saveAs(blob, "Resume_Agnesh.pdf"); // Replace 'filename.ext' with the desired file name and extension
    //   })
    //   .catch((error) => {
    //     console.error("Error downloading the file:", error);
    //   });

    const link = document.createElement("a");
    link.href =
      "https://drive.google.com/file/d/1H7leexzj77C2md2vfG9OdlTZDVIB5PkQ/view?usp=sharing";
    link.download = "agnesh_resume.pdf"; // Specify the desired file name

    link.dispatchEvent(
      new MouseEvent("click", {
        bubbles: true,
        cancelable: true,
        view: window,
      })
    );
  };

  return (
    <div className={darkMode ? "dark" : ""} style={{ height: 100 }}>
      <Head>
        <title>Agnesh's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-4 dark:bg-gray-900 lg:px-20">
        <section className="flex min-h-screen flex-col justify-between ">
          <nav className="mb-12 flex justify-between py-10 ">
            <div className="flex w-1/2 flex-row  text-center">
              {!isLargeScreen && <MobileNav setIsActive={setCurrentPage} />}
              <button
                className="ml-12 text-start font-poppins_semi_bold text-xl dark:text-white lg:ml-0"
                onClick={() => {
                  setCurrentPage(pages.home);
                }}
              >
                My Portfolio
              </button>
              {isLargeScreen && (
                <ul className=" ml-10 flex w-60 flex-row justify-evenly dark:text-white">
                  <li className="text-x font-poppins_semi_bold dark:text-white">
                    <button onClick={() => setCurrentPage(pages.certificates)}>
                      Certificates
                    </button>
                  </li>
                  <li className="text-x font-poppins_semi_bold dark:text-white">
                    <button onClick={() => setCurrentPage(pages.projects)}>
                      Projects
                    </button>
                  </li>
                </ul>
              )}
            </div>
            <ul className=" flex items-center dark:text-white">
              <li className="text-2xl lg:text-3xl">
                {darkMode ? (
                  <FaSun onClick={() => setDarkMode(!darkMode)} />
                ) : (
                  <FaMoon onClick={() => setDarkMode(!darkMode)} />
                )}
              </li>
              <li>
                {/* <a
                  className=" ml-8 rounded-lg bg-gradient-to-r from-violet-500 to-purple-500 px-4 py-2 text-white hover:from-red-600 hover:to-red-500"
                  href="https://drive.google.com/uc?id=1okf-B-7W9KXgXtGU8aUrM7-5RGym_JCG"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  Download File
                </a> */}

                <a
                  className=" ml-8 cursor-pointer rounded-lg bg-gradient-to-r from-violet-500 to-purple-500 px-4 py-2 text-white hover:from-red-600 hover:to-red-500"
                  onClick={() => {
                    downloadResume();
                  }}
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          {currentPage == pages.home && <Intro />}
          {currentPage == pages.home && <NodeGraphSkills isLargeScreen={isLargeScreen}/>}
          {currentPage == pages.home && <Contact />}
          {currentPage == pages.certificates && <Certificates />}
          {currentPage == pages.projects && <Projects />}
        </section>
      </main>
    </div>
  );
};

export default Home;
