import Head from "next/head";
import { FaSun, FaMoon } from "react-icons/fa";
import { useEffect, useState } from "react";
import Intro from "./Intro";
import Skills from "./skills";
import NodeGraphSkills from "./NodeGraphSkills";

const Home = function () {
  const [darkMode, setDarkMode] = useState(true);
  const [isLargeScreen, setIsLargeScreen] = useState(false);

  useEffect(() => {
    const handleResize = () => {
      setIsLargeScreen(window.innerWidth >= 768);
    };
    window.addEventListener("resize", handleResize);
    handleResize();
    return () => window.removeEventListener("resize", handleResize);
  }, []);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Agnesh's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-4 dark:bg-gray-900 lg:px-10">
        <section className="flex min-h-screen flex-col justify-between">
          <nav className="mb-12 flex justify-between py-10 ">
            <h1 className=" font-poppins_semi_bold text-xl dark:text-white">
              My Portfolio
            </h1>
            <ul className=" flex items-center dark:text-white">
              <li className=" text-2xl lg:text-3xl">
                {darkMode ? (
                  <FaSun onClick={() => setDarkMode(!darkMode)} />
                ) : (
                  <FaMoon onClick={() => setDarkMode(!darkMode)} />
                )}
              </li>
              <li>
                <a
                  className=" ml-8 rounded-lg bg-gradient-to-r from-violet-500 to-purple-500 px-4 py-2 text-white hover:from-red-600 hover:to-red-500"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <Intro mode={darkMode} />
          <NodeGraphSkills />
        </section>
      </main>
    </div>
  );
};

export default Home;
